---
title: "Model Exploration A"
author: "Matthew Walker"
format: pdf
---

```{r, libraries, include = F}
library(tidyverse)
library(tidymodels)
library(vroom)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(tigris)
library(corrplot)
library(MASS)
library(glmnet)
options(tigris_use_cache = TRUE)
```

```{r, reading in data, include = F}
rats_data <- vroom("rats.csv")
council_data <- vroom("councils.csv")
```

```{r, prepping spatial data}
# # This code was written with help from Microsoft Copilot
# 
# # rats layer
# rats_sf <- rats_data %>%
#   filter(!(is.na(Longitude)) & !(is.na(Latitude))) %>%
#   st_as_sf(.,
#   coords = c("Longitude", "Latitude"),
#   crs = 4326
# )
# 
# # New York layer
# nyc <- county_subdivisions(state = "NY", year = 2023, class = "sf") %>%
#   filter(COUNTYFP %in% c("005", "047", "061", "081", "085"))
# 
# # background layers
# # reading in background
# land  <- ne_download(scale = 10, type = "land",  category = "physical", returnclass = "sf")
# ocean <- ne_download(scale = 10, type = "ocean", category = "physical", returnclass = "sf")
# 
# # cutting down background to just NYC
# sf_use_s2(FALSE)
# nyc_bbox_wgs <- st_transform(st_as_sfc(st_bbox(nyc)), 4326)
# land_nyc  <- st_intersection(land,  nyc_bbox_wgs)
# ocean_nyc <- st_intersection(ocean, nyc_bbox_wgs)
# sf_use_s2(TRUE)
# 
# # prepping the layers to go together
# nyc_2263 <- st_transform(nyc, 2263)
# rats_2263 <- st_transform(rats_sf, 2263)
# land_2263 <- st_transform(land_nyc, 2263)
# ocean_2263 <- st_transform(ocean_nyc, 2263)

```

```{r, making map}
# # This code was written with help from Microsoft Copilot
# 
# ggplot() +
#   geom_sf(data = ocean_2263, fill = "#a6cee3", color = NA) +
#   geom_sf(data = land_2263,  fill = "gray95", color = NA) +
#   # geom_sf(data = nyc_2263, fill = "gray", alpha = 0.5) +
#   geom_sf(data = rats_2263, color = "blue", alpha = 0.05)
```

```{r, EDA}
# setting desired predictors
desired_variables <- c(
  # "reports",
  "population",
  "housing_units",
  "median_household_income",
  "unemployment_rate",
  "poverty_rate",
  # "pct_vacant_housing_units",
  "pct_renter_occupied_among_occupied_units",
  # "rental_vacancy_rate",
  "median_home_value",
  "pct_bachelors_or_higher_proxy",
  "pct_high_school_grad_proxy",
  "pct_households_broadband",
  "pct_with_disability_proxy",
  "pct_language_other_than_english_proxy"
  # "Council District"
)

council_data %>%
  
  # removing duplicate column
  dplyr::select(-council_district_name) %>%
  
  # cutting down data for sanity
  dplyr::select(all_of(c("reports", desired_variables, "Council District"))) %>%
  
  cor(.) %>%
  corrplot(., tl.cex = 0.5)
```

```{r, fitting negative binomial model}
fit_nb <- glm.nb(confirmed_reports ~ 
                 households + pct_renter_occupied_among_occupied_units,
  # as.formula(
                            # paste("reports ~",
                            # paste(desired_variables, collapse = " + "))),
                 data = council_data)

summary(fit_nb)

fit_nb
```

```{r, basic linear model}
fit_lm <- lm(as.formula(paste("reports ~",
                              paste(desired_variables, collapse = " + "))),
                 data = council_data)

summary(fit_lm)
```

```{r, LASSO model}
x <- as.matrix(scale(council_data[, -c(1:3, 27, 28)]))
y <- council_data$reports

fit_lasso <- cv.glmnet(x, y, alpha = 1)

fit_lasso$lambda.min
fit_lasso$lambda.1se

coef(fit_lasso, s = "lambda.min")
coef(fit_lasso, s = "lambda.1se")
coef(fit_lasso, s = 70)
```

```{r, predicted vs. actual values}
ggplot(mapping = aes(x = log(council_data$confirmed_reports))) +
  geom_point(aes(y = fit_confirmed$fitted.values), color = "red") +
  geom_point(aes(y = log(fit_nb$fitted.values)), color = "blue") +
  geom_point(aes(y = log(council_data$confirmed_reports)), color = "black")
```


```{r, LASSO model to extract most frequent cases}
x <- as.matrix(scale(council_data[, -c(1:4, 7:10, 27, 28)]))
y <- council_data$reports

fit_lasso_reports <- cv.glmnet(x, 
                      log(council_data$reports / council_data$population), alpha = 1)
fit_lasso_confirmed <- cv.glmnet(x, 
                      log(council_data$confirmed_reports / council_data$population), alpha = 1)
fit_lasso_ratio <- cv.glmnet(x[,-c(2, 11)], 
                      log(council_data$confirmed_reports / council_data$reports),
                      alpha = 1)

coef(fit_lasso_reports, s = 0.1)
coef(fit_lasso_confirmed, s = 0.07)
coef(fit_lasso_ratio, s = 0.05)
```


```{r, getting CI's for coefficients found with LASSO}
x <- as.matrix(scale(council_data[, -c(1:4, 7:10, 27, 28)]))
y <- council_data$reports

fit_lasso_reports <- cv.glmnet(x, 
                      log(council_data$reports/council_data$population), alpha = 1,
                      family = "gaussian")
fit_lasso_confirmed <- cv.glmnet(x, 
                      log(council_data$confirmed_reports/council_data$population), alpha = 1,
                      family = "gaussian")
fit_lasso_ratio <- cv.glmnet(x, 
                      log(council_data$confirmed_reports / council_data$reports),
                      alpha = 1)

fit_reports <- lm(log(reports/population) ~ 
                    # households +
                    pct_renter_occupied_among_occupied_units +
                    pct_language_other_than_english_proxy +
                    pct_households_broadband,
                  data = council_data)
fit_confirmed <- lm(log(confirmed_reports/population) ~ 
                      # households +
                      pct_renter_occupied_among_occupied_units +
                      pct_language_other_than_english_proxy +
                      pct_households_broadband,
                  data = council_data)
fit_ratio <- lm(log(confirmed_reports / reports) ~
                  population +
                  # pct_renter_occupied_among_occupied_units +
                  rental_vacancy_rate +
                  median_home_value,
                  data = council_data)


summary(fit_reports)
summary(fit_confirmed)
summary(fit_ratio)
```

```{r, making graphic}
council_data %>%
  ggplot(mapping = aes(x = pct_renter_occupied_among_occupied_units,
                       y = confirmed_reports / population * 1000)) +
  geom_point(color = "gray40") +
  geom_smooth(method = "lm", se = F) +
  scale_y_continuous(transform = "log10",
                     breaks = c(0.25, 0.5, 1.0, 2.0)) +
  scale_x_continuous(breaks = c(0.2, 0.4, 0.6, 0.8),
                     labels = c("20%", "40%", "60%", "80%")) +
  labs(title = "Rate of Confirmed Rodent Reports By Percent of Housing Units Rented",
       x = "Percent of Housing Units Occupied As Rentals",
       y = "Confirmed Rodent Reports Per 1000 People")
```

```{r, reporting final values}
```